cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'curl'
brew 'docker'
brew 'docker-compose'
brew 'nmap'
brew 'openssl'
brew 'python'
brew 'ruby'
brew 'spark'

cask 'atom'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'github-desktop'
cask 'keybase'
cask 'mysqlworkbench'
cask 'slack'
cask 'virtualbox'
